spring.application.name=monolitico

# Configuración H2 en memoria
spring.datasource.url=jdbc:h2:mem:monolitico_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
